# Generated by Django 6.0.6 on 2026-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/%Y/%m/'),
        ),
    ]
